environment: dev

backend:
  replicas: 1
  image:
    repository: caatch-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8000

frontend:
  replicas: 1
  image:
    repository: caatch-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 3000

cockroach:
  enabled: true
  host: ""
  port: 26257
  image:
    repository: cockroachdb/cockroach
    tag: v23.2.11
  storage:
    size: 1Gi
  user: root
  password: ""
  database: caatch

ingress:
  enabled: true
  className: nginx
