environment: prod

backend:
  replicas: 3
  image:
    tag: prod-stable

frontend:
  replicas: 3
  image:
    tag: prod-stable

cockroach:
  enabled: false
  host: cockroach-prod.example.com
  port: 26257
  user: root
  password: ""
  database: caatch_prod
