environment: staging

backend:
  replicas: 2
  image:
    tag: staging-stable

frontend:
  replicas: 2
  image:
    tag: staging-stable

cockroach:
  enabled: false
  host: cockroach-staging.example.com
  port: 26257
  user: root
  password: ""
  database: caatch_staging
