apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caatch.fullname" . }}-frontend
  labels:
    {{- include "caatch.labels" . | nindent 4 }}
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "caatch.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "caatch.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        env:
        - name: ENVIRONMENT
          value: {{ .Values.environment | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caatch.fullname" . }}-frontend
  labels:
    {{- include "caatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  selector:
    {{- include "caatch.selectorLabels" . | nindent 4 }}
    app: frontend
